### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by sergeyklay**
See diff

### CODE REVIEW

**Comment by AbdouYoha** [comment]
Hi Sergey and ALL,

I'm  new in Kohana :-)

I have a pb to display the captcha image: in the captcha controller I put : 

public function action_index($group = 'default')
    {
        // Output the Captcha challenge resource (no html)
        // Pull the config group name from the URL

```
    $captcha = Captcha::instance();
            echo $captcha->render(TRUE);
```

But I have only the width and the height of the image and No things else!
Thank you for your help

**Comment by sergeyklay** [comment]
@AbdouYoha

Hmm, are you sure that your code

``` php
public function action_index($group = 'default')
{
   ...
}
```

is correct?

May be:

``` php
public function action_index()
{
   $group = $this->request->param('group', 'default');
   ...
}
```

**Comment by AbdouYoha** [comment]
Thank you for response.
 But no thing has changed with or without $group as parameter !

I"ll try that: https://bitbucket.org/dev4dev/kohana-recaptcha/src/7ada54e1fc56/classes/recaptcha.php?at=default

**Comment by sergeyklay** [comment]
@AbdouYoha
Do you want me to teach you to use it right here? ;)

**Comment by AbdouYoha** [comment]
Thank you very much, You are very Kind.
For the moment, I used the reCaptcha (of Google)
I'll be back to Kohana Captcha ASAP. And  I 'would contact you if  I don't resolve the pb
Regards,

**Pull request closed without merging**
